### ISSUE TITLE
rviz of car's moving

### ISSUE THREAD

**Issue by xiaozhi12345678** [coincar-sim/lanelet_rviz_plugin_ros#4] opened 2019-04-19 14:50 UTC
Hi,I want to ask a question.If I want to make the car in rviz move by my publishing GPS or (x,y)position message,how can I do it?than you!

**Comment by m-naumann** [comment] 2019-05-06 22:00
Duplicate of https://github.com/coincar-sim/coincarsim_getting_started/issues/4

**Closed as completed by m-naumann** 2019-05-06 22:00 UTC
